language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
    - jq # For parsing JSON

git:
  depth: false # Allows Git operations

install: skip

script:
  - ./gradlew build

before_deploy:
  - .travis/before_deploy.sh

deploy:
  - provider: pages
    github-token:
      secure: hB6wJ7+uozulcGUnSPQ0LceKK3Z+6cvB2HLoEv9jrx00JuT4+rsIKmWJZbOVvUlxmabCRevn0frR5kz3mNZZCsyQUoZLw973hM+xRaeFnwmWOkh8YdmXLnEmNagGquDkxYRh6MtZuvYANQcOaV2OkuF2/f+DzOxvHXu4x7eVb5IwdMqe5A8EUQdLcl03A3xNT1s9nVJxU49mCBT7l8cqmTnhAZV0ItgqDzxKz7q1pCRTgv9Wy/zRLR0Q64xgnXU3QIw1l5CcPsm7oTl92T53TMHck08wJ+1SbSLIHOQJl4n2ru3HFotC07qGmIpoTbKvlkx1/akSeCK7Q6RmKCyrdoryLLIefEv+Mv0dpeVrJ83ZlcVoyE21FltGOkNmLmNBpCT2gSNGzgPSIRFxeGUtUOs3da2l3UWqXmnd5HoJVJ9tVvW/ekpRc9lXeAw0FlP13ArRkI3OtQLDF42dfS27DsXiKo5vYwrNWSZoDNjqOASz6nc7tGxxzJto+J+M3g+btmtCt8uvcopfin5TFd6w14xM1RCGqTVBwkJrNCeopX2BPHjWaBUsKw0+8w+c7+DlAFPaYkySNM/Spgp2Xi9yev0CUIBTx8wdy6D2tZaehS8E9Yds9PSEog5Po4XQlHVb4efqf+zMu8Ca3MHTRfyD8Nz1Gjc+8OhmE6suCX5MU/0=
    email: Leo3418@users.noreply.github.com
    name: Leo
    local-dir: .travis/pages
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key:
      secure: hB6wJ7+uozulcGUnSPQ0LceKK3Z+6cvB2HLoEv9jrx00JuT4+rsIKmWJZbOVvUlxmabCRevn0frR5kz3mNZZCsyQUoZLw973hM+xRaeFnwmWOkh8YdmXLnEmNagGquDkxYRh6MtZuvYANQcOaV2OkuF2/f+DzOxvHXu4x7eVb5IwdMqe5A8EUQdLcl03A3xNT1s9nVJxU49mCBT7l8cqmTnhAZV0ItgqDzxKz7q1pCRTgv9Wy/zRLR0Q64xgnXU3QIw1l5CcPsm7oTl92T53TMHck08wJ+1SbSLIHOQJl4n2ru3HFotC07qGmIpoTbKvlkx1/akSeCK7Q6RmKCyrdoryLLIefEv+Mv0dpeVrJ83ZlcVoyE21FltGOkNmLmNBpCT2gSNGzgPSIRFxeGUtUOs3da2l3UWqXmnd5HoJVJ9tVvW/ekpRc9lXeAw0FlP13ArRkI3OtQLDF42dfS27DsXiKo5vYwrNWSZoDNjqOASz6nc7tGxxzJto+J+M3g+btmtCt8uvcopfin5TFd6w14xM1RCGqTVBwkJrNCeopX2BPHjWaBUsKw0+8w+c7+DlAFPaYkySNM/Spgp2Xi9yev0CUIBTx8wdy6D2tZaehS8E9Yds9PSEog5Po4XQlHVb4efqf+zMu8Ca3MHTRfyD8Nz1Gjc+8OhmE6suCX5MU/0=
    file_glob: true # Enables wildcard
    file: build/libs/*
    skip_cleanup: true
    on:
      tags: true
