language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
    - jq # For parsing JSON

git:
  depth: false # Allows Git operations

install:
  - ./gradlew setupCiWorkspace

script:
  - ./gradlew build

before_deploy:
  - .travis/before_deploy.sh

deploy:
  - provider: pages
    github-token:
      secure: o1Rwmdfon/fSVHWr3cMj0WxB9wvLWoHizanMXu7+RWTULwuaU1nEqbpWiskHRtba9FbhbAASLAR5rpjfMewSRZS9W3h1tYzwTJK7jgdsQ4i1u8ykC2TzR6EYoMMIhk+QHoGppfNjVyKKVbjRdWjTh89nADg2S9e6qCz3OQFEVDmyieZGbWeTneklgezfG1w1o+Ic5rWbZqfba+IkLAAEaNecgA1jebUTQlHDcf9X0EzofaLJP7I99K2M+lLX9HaE4MJAuvRAOW7ovYcOsSFMy2FTk/r9OV3YHfQD2ADfUjH6cF/Be+5BYG6C9smPGGkJ9QisRFe1eco6p86Eib6dUDi6HYM5l07w5H+ceSvMADD69wxiG401Bo65e/VqUQP7YUSi8tU0/JY2NSrDICt/a5vndwXw1CGSDoMaQUIPIgBjJUVPxzPV0ifRFA9mJQHO0Qf+Onf6oMbPXVrUc13NuyXpWPs/IaIJ4WXnRPxsZBdpugaUHR7d8ahmB2hrPiKIzvszQyLCniDYiY0tcCm0KUauBl7uIsE4wgR42QbYzaJCo/xzx0ezN5Zr33A1UmQIu6RaQ8QLYEw0sqyYOWz8IZb6C0Y/XmWEOkTaR+Rm6/ZVeM7lRSoZpxe9RWOBF4nzx6964o0P0jBoHLTIE7uKarCMNzte9YxSrehZC0LREZI=
    email: Leo3418@users.noreply.github.com
    name: Leo
    local-dir: .travis/pages
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key:
      secure: o1Rwmdfon/fSVHWr3cMj0WxB9wvLWoHizanMXu7+RWTULwuaU1nEqbpWiskHRtba9FbhbAASLAR5rpjfMewSRZS9W3h1tYzwTJK7jgdsQ4i1u8ykC2TzR6EYoMMIhk+QHoGppfNjVyKKVbjRdWjTh89nADg2S9e6qCz3OQFEVDmyieZGbWeTneklgezfG1w1o+Ic5rWbZqfba+IkLAAEaNecgA1jebUTQlHDcf9X0EzofaLJP7I99K2M+lLX9HaE4MJAuvRAOW7ovYcOsSFMy2FTk/r9OV3YHfQD2ADfUjH6cF/Be+5BYG6C9smPGGkJ9QisRFe1eco6p86Eib6dUDi6HYM5l07w5H+ceSvMADD69wxiG401Bo65e/VqUQP7YUSi8tU0/JY2NSrDICt/a5vndwXw1CGSDoMaQUIPIgBjJUVPxzPV0ifRFA9mJQHO0Qf+Onf6oMbPXVrUc13NuyXpWPs/IaIJ4WXnRPxsZBdpugaUHR7d8ahmB2hrPiKIzvszQyLCniDYiY0tcCm0KUauBl7uIsE4wgR42QbYzaJCo/xzx0ezN5Zr33A1UmQIu6RaQ8QLYEw0sqyYOWz8IZb6C0Y/XmWEOkTaR+Rm6/ZVeM7lRSoZpxe9RWOBF4nzx6964o0P0jBoHLTIE7uKarCMNzte9YxSrehZC0LREZI=
    file_glob: true # Enables wildcard
    file: build/libs/*
    skip_cleanup: true
    on:
      tags: true
